package ru.tigran.telegram.bots.api.model.enums

enum class UpdateType {
    MESSAGE,
    EDITED_MESSAGE,
    CHANNEL_POST,
    EDITED_CHANNEL_POST,
    BUSINESS_CONNECTION,
    BUSINESS_MESSAGE,
    EDITED_BUSINESS_MESSAGE,
    DELETED_BUSINESS_MESSAGES,
    MESSAGE_REACTION,
    MESSAGE_REACTION_COUNT,
    INLINE_QUERY,
    CHOSEN_INLINE_RESULT,
    CALLBACK_QUERY,
    SHIPPING_QUERY,
    PRE_CHECKOUT_QUERY,
    POLL,
    POLL_ANSWER,
    MY_CHAT_MEMBER,
    CHAT_MEMBER,
    CHAT_JOIN_REQUEST,
    CHAT_BOOST,
    REMOVED_CHAT_BOTS,

    UNKNOWN,
}